# Generated by Django 3.1.1 on 2020-09-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200906_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konto',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
