# Generated by Django 3.1.1 on 2020-09-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200906_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Konto',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='account',
        ),
    ]
